type StateView = struct {
  counter: u64,
  last_caller: opt actor_id,
  ping_count: u64,
  message_count: u32,
};

type StoredMessage = struct {
  sender: actor_id,
  text: str,
  block_height: u32,
};

constructor {
  Create : ();
};

service Demo {
  Increment : () -> u64;
  SendMessage : (text: str) -> str;
  SchedulePing : (delay: u32) -> null;
  HandlePing : () -> null;
  query GetCounter : () -> u64;
  query GetMessages : () -> vec StoredMessage;
  query GetState : () -> StateView;
};
