// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Regenerate: cd frontend && ./node_modules/.bin/tsx ../scripts/scaffold-client.ts
// Feel free to customize — re-running the script will overwrite this file.

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  CheckCircle, CircleNotch, Clock, PlusCircle, XCircle,
} from "@phosphor-icons/react";
import { useChainApi, useWallet } from "@/providers/chain-provider";
import { initSails } from "@/lib/sails-client";

type TxPhase = "idle" | "signing" | "submitted" | "confirmed" | "error";

function TxStatus({
  phase, error, onDismiss,
}: {
  phase: TxPhase; error: string | null; onDismiss?: () => void;
}) {
  return (
    <AnimatePresence mode="wait">
      {phase !== "idle" && (
        <motion.div key={phase} initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 4 }} transition={{ type: "spring" as const, stiffness: 200, damping: 25 }} className={`mt-2.5 ${phase === "error" ? "bg-red-500/5 border border-red-500/10 rounded-xl p-3" : "flex items-center gap-1.5"}`}>
          {phase === "signing" && (<><CircleNotch size={14} className="animate-spin text-amber-400" /><span className="text-sm text-amber-400">Waiting for signature</span></>)}
          {phase === "submitted" && (<><CircleNotch size={14} className="animate-spin text-emerald-400" /><span className="text-sm text-emerald-400">Processing</span></>)}
          {phase === "confirmed" && (<><CheckCircle size={14} weight="fill" className="text-emerald-400" /><span className="text-sm text-emerald-400">Confirmed</span></>)}
          {phase === "error" && (<div className="flex items-start gap-2"><XCircle size={16} weight="fill" className="text-red-400 mt-0.5 flex-shrink-0" /><span className="text-sm text-red-400 flex-1">{error}</span>{onDismiss && (<button onClick={onDismiss} className="text-red-400/60 hover:text-red-300 transition-colors flex-shrink-0"><XCircle size={14} weight="bold" /></button>)}</div>)}
        </motion.div>
      )}
    </AnimatePresence>
  );
}

export function ActionsPanel({ onTxSuccess }: { onTxSuccess: () => void }) {
  const { api, apiStatus } = useChainApi();
  const { account, signer, walletStatus } = useWallet();
  const disabled = !api || apiStatus !== "ready" || walletStatus !== "connected" || !account;

  // HandlePing
  const [hanPhase, setHandlePingPhase] = useState<TxPhase>("idle");
  const [hanError, setHandlePingError] = useState<string | null>(null);

  // Increment
  const [incPhase, setIncrementPhase] = useState<TxPhase>("idle");
  const [incError, setIncrementError] = useState<string | null>(null);

  // SchedulePing
  const [schPhase, setSchedulePingPhase] = useState<TxPhase>("idle");
  const [schError, setSchedulePingError] = useState<string | null>(null);
  const [schDelay, setSchedulePingDelay] = useState(0);

  // SendMessage
  const [senPhase, setSendMessagePhase] = useState<TxPhase>("idle");
  const [senError, setSendMessageError] = useState<string | null>(null);
  const [senText, setSendMessageText] = useState("");

  // SetGreeting
  const [setPhase, setSetGreetingPhase] = useState<TxPhase>("idle");
  const [setError, setSetGreetingError] = useState<string | null>(null);
  const [setGreeting, setSetGreetingGreeting] = useState("");

  async function handleHandlePing() {
    if (!api || !account) return;
    setHandlePingPhase("signing");
    setHandlePingError(null);
    try {
      const sails = await initSails(api);
      const service = sails?.services?.Demo ?? sails?.services?.demo;
      const tx = service.functions.HandlePing();
      tx.withAccount(account.address, signer ? { signer } : undefined);
      await tx.calculateGas();
      setHandlePingPhase("submitted");
      const result = await tx.signAndSend();
      await result.response();
      setHandlePingPhase("confirmed");
      onTxSuccess();
      setTimeout(() => setHandlePingPhase("idle"), 3000);
    } catch (err) {
      setHandlePingPhase("error");
      setHandlePingError(err instanceof Error ? err.message : "Transaction failed");
    }
  }

  async function handleIncrement() {
    if (!api || !account) return;
    setIncrementPhase("signing");
    setIncrementError(null);
    try {
      const sails = await initSails(api);
      const service = sails?.services?.Demo ?? sails?.services?.demo;
      const tx = service.functions.Increment();
      tx.withAccount(account.address, signer ? { signer } : undefined);
      await tx.calculateGas();
      setIncrementPhase("submitted");
      const result = await tx.signAndSend();
      await result.response();
      setIncrementPhase("confirmed");
      onTxSuccess();
      setTimeout(() => setIncrementPhase("idle"), 3000);
    } catch (err) {
      setIncrementPhase("error");
      setIncrementError(err instanceof Error ? err.message : "Transaction failed");
    }
  }

  async function handleSchedulePing() {
    if (!api || !account) return;
    if (schDelay < 1) {
      setSchedulePingError("delay must be at least 1");
      setSchedulePingPhase("error");
      return;
    }
    setSchedulePingPhase("signing");
    setSchedulePingError(null);
    try {
      const sails = await initSails(api);
      const service = sails?.services?.Demo ?? sails?.services?.demo;
      const tx = service.functions.SchedulePing(schDelay);
      tx.withAccount(account.address, signer ? { signer } : undefined);
      await tx.calculateGas();
      setSchedulePingPhase("submitted");
      const result = await tx.signAndSend();
      await result.response();
      setSchedulePingPhase("confirmed");
      onTxSuccess();
      setTimeout(() => setSchedulePingPhase("idle"), 3000);
    } catch (err) {
      setSchedulePingPhase("error");
      setSchedulePingError(err instanceof Error ? err.message : "Transaction failed");
    }
  }

  async function handleSendMessage() {
    if (!api || !account) return;
    if (!senText || !senText.trim()) {
      setSendMessageError("text cannot be empty");
      setSendMessagePhase("error");
      return;
    }
    setSendMessagePhase("signing");
    setSendMessageError(null);
    try {
      const sails = await initSails(api);
      const service = sails?.services?.Demo ?? sails?.services?.demo;
      const tx = service.functions.SendMessage(senText);
      tx.withAccount(account.address, signer ? { signer } : undefined);
      await tx.calculateGas();
      setSendMessagePhase("submitted");
      const result = await tx.signAndSend();
      await result.response();
      setSendMessagePhase("confirmed");
      onTxSuccess();
      setTimeout(() => setSendMessagePhase("idle"), 3000);
    } catch (err) {
      setSendMessagePhase("error");
      setSendMessageError(err instanceof Error ? err.message : "Transaction failed");
    }
  }

  async function handleSetGreeting() {
    if (!api || !account) return;
    if (!setGreeting || !setGreeting.trim()) {
      setSetGreetingError("greeting cannot be empty");
      setSetGreetingPhase("error");
      return;
    }
    setSetGreetingPhase("signing");
    setSetGreetingError(null);
    try {
      const sails = await initSails(api);
      const service = sails?.services?.Demo ?? sails?.services?.demo;
      const tx = service.functions.SetGreeting(setGreeting);
      tx.withAccount(account.address, signer ? { signer } : undefined);
      await tx.calculateGas();
      setSetGreetingPhase("submitted");
      const result = await tx.signAndSend();
      await result.response();
      setSetGreetingPhase("confirmed");
      onTxSuccess();
      setTimeout(() => setSetGreetingPhase("idle"), 3000);
    } catch (err) {
      setSetGreetingPhase("error");
      setSetGreetingError(err instanceof Error ? err.message : "Transaction failed");
    }
  }

  const busy = hanPhase === "signing" || hanPhase === "submitted" || incPhase === "signing" || incPhase === "submitted" || schPhase === "signing" || schPhase === "submitted" || senPhase === "signing" || senPhase === "submitted" || setPhase === "signing" || setPhase === "submitted";

  return (
    <div className="rounded-2xl border border-zinc-800/50 bg-zinc-900/30 p-6 shadow-[0_8px_30px_-12px_rgba(0,0,0,0.4)]">
      <h2 className="text-sm font-medium text-zinc-400 mb-5">Actions</h2>

      {!account && (
        <div className="py-6 text-center">
          <p className="text-sm text-zinc-400">Connect your wallet to send transactions.</p>
        </div>
      )}

      <div className="space-y-0 divide-y divide-zinc-800/50">
        {/* HandlePing */}
        <div className="pb-5">
          <button
            onClick={handleHandlePing}
            disabled={disabled || busy}
            className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-emerald-600/80 text-emerald-50 text-base font-medium hover:bg-emerald-600 transition-all disabled:opacity-30 disabled:cursor-not-allowed active:scale-[0.97]"
          >
            <Clock size={16} weight="bold" />
            HandlePing
          </button>
          <TxStatus phase={hanPhase} error={hanError} onDismiss={() => { setHandlePingPhase("idle"); setHandlePingError(null); }} />
        </div>
        {/* Increment */}
        <div className="py-5">
          <button
            onClick={handleIncrement}
            disabled={disabled || busy}
            className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-emerald-600/80 text-emerald-50 text-base font-medium hover:bg-emerald-600 transition-all disabled:opacity-30 disabled:cursor-not-allowed active:scale-[0.97]"
          >
            <PlusCircle size={16} weight="bold" />
            Increment
          </button>
          <TxStatus phase={incPhase} error={incError} onDismiss={() => { setIncrementPhase("idle"); setIncrementError(null); }} />
        </div>
        {/* SchedulePing */}
        <div className="py-5">
          <label className="block text-sm text-zinc-400 font-medium mb-2">SchedulePing</label>
          <div className="flex gap-2 items-center">
            <input type="number" value={schDelay} onChange={(e) => setSchedulePingDelay(Number(e.target.value))} className="w-24 px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm font-mono border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-all" />
            <span className="text-sm text-zinc-400">delay</span>
            <button onClick={handleSchedulePing} disabled={disabled || busy} className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-zinc-800 text-zinc-300 text-sm hover:bg-zinc-700 transition-all disabled:opacity-30 active:scale-[0.97] ml-auto">SchedulePing</button>
          </div>
          <TxStatus phase={schPhase} error={schError} onDismiss={() => { setSchedulePingPhase("idle"); setSchedulePingError(null); }} />
        </div>
        {/* SendMessage */}
        <div className="py-5">
          <label className="block text-sm text-zinc-400 font-medium mb-2">SendMessage</label>
          <div className="flex gap-2 items-center">
            <div className="flex-1 relative">
              <input type="text" value={senText} onChange={(e) => setSendMessageText(e.target.value)} placeholder="text..." className="w-full px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-all placeholder:text-zinc-500" />
              {senText.length > 0 && <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-zinc-600">{senText.length}</span>}
            </div>
            <button onClick={handleSendMessage} disabled={disabled || busy} className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-zinc-800 text-zinc-300 text-sm hover:bg-zinc-700 transition-all disabled:opacity-30 active:scale-[0.97] ml-auto">SendMessage</button>
          </div>
          <TxStatus phase={senPhase} error={senError} onDismiss={() => { setSendMessagePhase("idle"); setSendMessageError(null); }} />
        </div>
        {/* SetGreeting */}
        <div className="pt-5">
          <label className="block text-sm text-zinc-400 font-medium mb-2">SetGreeting</label>
          <div className="flex gap-2 items-center">
            <div className="flex-1 relative">
              <input type="text" value={setGreeting} onChange={(e) => setSetGreetingGreeting(e.target.value)} placeholder="greeting..." className="w-full px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-all placeholder:text-zinc-500" />
              {setGreeting.length > 0 && <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-zinc-600">{setGreeting.length}</span>}
            </div>
            <button onClick={handleSetGreeting} disabled={disabled || busy} className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-zinc-800 text-zinc-300 text-sm hover:bg-zinc-700 transition-all disabled:opacity-30 active:scale-[0.97] ml-auto">SetGreeting</button>
          </div>
          <TxStatus phase={setPhase} error={setError} onDismiss={() => { setSetGreetingPhase("idle"); setSetGreetingError(null); }} />
        </div>
      </div>
    </div>
  );
}
