// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Regenerate: cd frontend && ./node_modules/.bin/tsx ../scripts/scaffold-client.ts
// Feel free to customize — re-running the script will overwrite this file.

import { useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { ArrowsClockwise, Pulse } from "@phosphor-icons/react";
import { CopyAddress } from "@/components/CopyAddress";
import { useChainApi, useWallet } from "@/providers/chain-provider";
import {
  queryMessages,
  queryState,
  type StoredMessage,
  type StateView,
} from "@/lib/sails-client";

function MetricRow({ value, label, accentColor = "border-emerald-500/40" }: { value: string | number; label: string; accentColor?: string }) {
  return (
    <div className={`border-l-2 ${accentColor} pl-4 py-2`}>
      <div className="font-mono text-3xl tracking-tighter text-zinc-300 leading-none">{String(value)}</div>
      <div className="text-sm text-zinc-400 mt-1.5">{label}</div>
    </div>
  );
}

function SkeletonMetric() {
  return (
    <div className="border-l-2 border-zinc-800 pl-4 py-2">
      <div className="h-9 w-16 rounded-lg bg-zinc-800/60 shimmer" />
      <div className="h-3 w-20 rounded bg-zinc-800/60 shimmer mt-2" />
    </div>
  );
}

export function StatePanel({ refreshTrigger }: { refreshTrigger: number }) {
  const { api, apiStatus, programId } = useChainApi();
  const { account } = useWallet();
  const [messagesData, setMessagesData] = useState<StoredMessage[] | null>(null);
  const [stateData, setStateData] = useState<StateView | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pollInterval, setPollInterval] = useState(5000);

  const fetchState = useCallback(async () => {
    if (!api || apiStatus !== "ready") return;
    try {
      const [r_messages, r_state] = await Promise.all([
        queryMessages(api, programId),
        queryState(api, programId),
      ]);
      setMessagesData(r_messages);
      setStateData(r_state);
      setError(null);
      setLoading(false);
      setPollInterval(5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to read state");
      setLoading(false);
      setPollInterval((prev) => Math.min(prev * 2, 60000));
    }
  }, [api, apiStatus, programId]);

  useEffect(() => { fetchState(); }, [fetchState, refreshTrigger]);

  useEffect(() => {
    if (!api || apiStatus !== "ready") return;
    const id = setInterval(fetchState, pollInterval);
    return () => clearInterval(id);
  }, [api, apiStatus, fetchState, pollInterval]);

  return (
    <div className="rounded-2xl border border-zinc-800/50 bg-zinc-900/30 p-6 shadow-[0_8px_30px_-12px_rgba(0,0,0,0.4)]">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-sm font-medium text-zinc-400">Program State</h2>
        <button onClick={fetchState} className="p-2 rounded-lg text-zinc-400 hover:text-zinc-300 hover:bg-zinc-800/50 transition-colors active:scale-[0.93]">
          <ArrowsClockwise size={16} weight="bold" />
        </button>
      </div>

      {loading && !messagesData ? (
        <div className="space-y-6">
          <SkeletonMetric /><SkeletonMetric /><SkeletonMetric />
        </div>
      ) : error && !messagesData ? (
        <div className="rounded-xl bg-red-500/5 border border-red-500/10 p-4">
          <p className="text-sm text-red-400">{error}</p>
          <button onClick={fetchState} className="mt-2 text-sm text-red-400/80 underline underline-offset-2 hover:text-red-300">Try again</button>
        </div>
      ) : !messagesData ? (
        <div className="py-8 text-center">
          <Pulse size={32} weight="duotone" className="mx-auto text-zinc-500 mb-3" />
          <p className="text-sm text-zinc-400">{account ? "Waiting for data. Send a transaction to get started." : "Connect your wallet to read program state."}</p>
        </div>
      ) : (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}>
          <div className="space-y-5">
            {messagesData && messagesData.length > 0 && (
              <div className="border-t border-zinc-800/50 pt-4 mt-4">
                <h3 className="text-sm text-zinc-400 mb-3">Messages ({messagesData.length})</h3>
                <div className="max-h-48 overflow-y-auto overflow-x-hidden divide-y divide-zinc-800/30">
                  {messagesData.map((item: StoredMessage, i: number) => (
                    <div key={i} className="py-2 text-sm text-zinc-400 min-w-0">
                      <div className="flex items-start gap-2 min-w-0">
                        {item.sender && <CopyAddress address={String(item.sender)} />}
                        <span className="break-all">{String(item.text ?? "")}</span>
                        <span className="break-all">{String(item.block_height ?? "")}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
            <MetricRow value={stateData?.counter ?? 0} label="counter" accentColor="border-emerald-500/40" />
            {stateData?.last_caller && (
              <div className="flex items-center gap-2 text-sm text-zinc-400 py-2">
                <span>last_caller:</span>
                <CopyAddress address={String(stateData.last_caller)} />
              </div>
            )}
            <MetricRow value={stateData?.ping_count ?? 0} label="ping_count" accentColor="border-amber-500/40" />
            <MetricRow value={stateData?.message_count ?? 0} label="message_count" accentColor="border-sky-500/40" />
            <MetricRow value={stateData?.greeting ?? ""} label="greeting" accentColor="border-violet-500/40" />
          </div>
        </motion.div>
      )}
    </div>
  );
}
