// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DemoClientProgram;
impl sails_rs::client::Program for DemoClientProgram {}
pub trait DemoClient {
    type Env: sails_rs::client::GearEnv;
    fn demo(&self) -> sails_rs::client::Service<demo::DemoImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DemoClient for sails_rs::client::Actor<DemoClientProgram, E> {
    type Env = E;
    fn demo(&self) -> sails_rs::client::Service<demo::DemoImpl, Self::Env> {
        self.service(stringify!(Demo))
    }
}
pub trait DemoClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Constructor: initializes program state.
    fn create(self) -> sails_rs::client::PendingCtor<DemoClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DemoClientCtors
    for sails_rs::client::Deployment<DemoClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<DemoClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod demo {
    use super::*;
    pub trait Demo {
        type Env: sails_rs::client::GearEnv;
        /// Internal handler for delayed ping messages. Only callable by the program itself.
        fn handle_ping(&mut self) -> sails_rs::client::PendingCall<io::HandlePing, Self::Env>;
        /// Increment the counter by 1. Returns the new value.
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env>;
        /// Send a delayed message to self that triggers handle_ping after `delay` blocks.
        fn schedule_ping(
            &mut self,
            delay: u32,
        ) -> sails_rs::client::PendingCall<io::SchedulePing, Self::Env>;
        /// Store a message on-chain. Max 256 chars, non-empty.
        fn send_message(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SendMessage, Self::Env>;
        /// Get the current counter value.
        fn get_counter(&self) -> sails_rs::client::PendingCall<io::GetCounter, Self::Env>;
        /// Get stored messages (last 100).
        fn get_messages(&self) -> sails_rs::client::PendingCall<io::GetMessages, Self::Env>;
        /// Get a summary of the current state.
        fn get_state(&self) -> sails_rs::client::PendingCall<io::GetState, Self::Env>;
    }
    pub struct DemoImpl;
    impl<E: sails_rs::client::GearEnv> Demo for sails_rs::client::Service<DemoImpl, E> {
        type Env = E;
        fn handle_ping(&mut self) -> sails_rs::client::PendingCall<io::HandlePing, Self::Env> {
            self.pending_call(())
        }
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env> {
            self.pending_call(())
        }
        fn schedule_ping(
            &mut self,
            delay: u32,
        ) -> sails_rs::client::PendingCall<io::SchedulePing, Self::Env> {
            self.pending_call((delay,))
        }
        fn send_message(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SendMessage, Self::Env> {
            self.pending_call((text,))
        }
        fn get_counter(&self) -> sails_rs::client::PendingCall<io::GetCounter, Self::Env> {
            self.pending_call(())
        }
        fn get_messages(&self) -> sails_rs::client::PendingCall<io::GetMessages, Self::Env> {
            self.pending_call(())
        }
        fn get_state(&self) -> sails_rs::client::PendingCall<io::GetState, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(HandlePing () -> ());
        sails_rs::io_struct_impl!(Increment () -> u64);
        sails_rs::io_struct_impl!(SchedulePing (delay: u32) -> ());
        sails_rs::io_struct_impl!(SendMessage (text: String) -> String);
        sails_rs::io_struct_impl!(GetCounter () -> u64);
        sails_rs::io_struct_impl!(GetMessages () -> Vec<super::StoredMessage>);
        sails_rs::io_struct_impl!(GetState () -> super::StateView);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum DemoEvents {
            Incremented { new_value: u64, caller: ActorId },
            MessageSent { sender: ActorId, text: String },
            PingScheduled { delay: u32 },
            PingReceived { ping_count: u64 },
        }
        impl sails_rs::client::Event for DemoEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "Incremented",
                "MessageSent",
                "PingScheduled",
                "PingReceived",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for DemoImpl {
            type Event = DemoEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct StoredMessage {
    pub sender: ActorId,
    pub text: String,
    pub block_height: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct StateView {
    pub counter: u64,
    pub last_caller: Option<ActorId>,
    pub ping_count: u64,
    pub message_count: u32,
}
