// Code generated by sails-client-gen. DO NOT EDIT.
#![no_std]

#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DemoClientProgram;

impl DemoClientProgram {
    pub const ROUTE_ID_DEMO: u8 = 1;
}

impl sails_rs::client::Program for DemoClientProgram {}

pub trait DemoClient {
    type Env: sails_rs::client::GearEnv;
    fn demo(&self) -> sails_rs::client::Service<demo::DemoImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DemoClient for sails_rs::client::Actor<DemoClientProgram, E> {
    type Env = E;
    fn demo(&self) -> sails_rs::client::Service<demo::DemoImpl, Self::Env> {
        self.service(DemoClientProgram::ROUTE_ID_DEMO)
    }
}
pub trait DemoClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Constructor: initializes program state.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<DemoClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DemoClientCtors
    for sails_rs::client::Deployment<DemoClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<DemoClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> (), 0);
}

pub mod demo {
    use super::*;

    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[scale_info(crate = sails_rs::scale_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct StateView {
        pub counter: u64,
        pub last_caller: Option<ActorId>,
        pub ping_count: u64,
        pub message_count: u32,
    }
    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[scale_info(crate = sails_rs::scale_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct StoredMessage {
        pub sender: ActorId,
        pub text: String,
        pub block_height: u32,
    }

    pub trait Demo {
        type Env: sails_rs::client::GearEnv;
        /// Get the current counter value.
        fn get_counter(&self) -> sails_rs::client::PendingCall<io::GetCounter, Self::Env>;
        /// Get stored messages (last 100).
        fn get_messages(&self) -> sails_rs::client::PendingCall<io::GetMessages, Self::Env>;
        /// Get a summary of the current state.
        fn get_state(&self) -> sails_rs::client::PendingCall<io::GetState, Self::Env>;
        /// Internal handler for delayed ping messages. Only callable by the program itself.
        fn handle_ping(&mut self) -> sails_rs::client::PendingCall<io::HandlePing, Self::Env>;
        /// Increment the counter by 1. Returns the new value.
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env>;
        /// Send a delayed message to self that triggers handle_ping after `delay` blocks.
        fn schedule_ping(
            &mut self,
            delay: u32,
        ) -> sails_rs::client::PendingCall<io::SchedulePing, Self::Env>;
        /// Store a message on-chain. Max 256 chars, non-empty.
        fn send_message(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SendMessage, Self::Env>;
    }

    pub struct DemoImpl;

    impl sails_rs::client::Identifiable for DemoImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([132, 222, 231, 234, 122, 249, 152, 69]);
    }

    impl<E: sails_rs::client::GearEnv> Demo for sails_rs::client::Service<DemoImpl, E> {
        type Env = E;
        fn get_counter(&self) -> sails_rs::client::PendingCall<io::GetCounter, Self::Env> {
            self.pending_call(())
        }
        fn get_messages(&self) -> sails_rs::client::PendingCall<io::GetMessages, Self::Env> {
            self.pending_call(())
        }
        fn get_state(&self) -> sails_rs::client::PendingCall<io::GetState, Self::Env> {
            self.pending_call(())
        }
        fn handle_ping(&mut self) -> sails_rs::client::PendingCall<io::HandlePing, Self::Env> {
            self.pending_call(())
        }
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env> {
            self.pending_call(())
        }
        fn schedule_ping(
            &mut self,
            delay: u32,
        ) -> sails_rs::client::PendingCall<io::SchedulePing, Self::Env> {
            self.pending_call((delay,))
        }
        fn send_message(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SendMessage, Self::Env> {
            self.pending_call((text,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GetCounter () -> u64, 0, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetMessages () -> Vec<super::StoredMessage>, 1, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetState () -> super::StateView, 2, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(HandlePing () -> (), 3, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Increment () -> u64, 4, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SchedulePing (delay: u32) -> (), 5, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SendMessage (text: String) -> String, 6, <super::DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum DemoEvents {
            #[codec(index = 0)]
            Incremented { new_value: u64, caller: ActorId },
            #[codec(index = 1)]
            MessageSent { sender: ActorId, text: String },
            #[codec(index = 2)]
            PingReceived { ping_count: u64 },
            #[codec(index = 3)]
            PingScheduled { delay: u32 },
        }

        impl DemoEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Incremented { .. } => 0,
                    Self::MessageSent { .. } => 1,
                    Self::PingReceived { .. } => 2,
                    Self::PingScheduled { .. } => 3,
                }
            }
        }

        impl sails_rs::client::Event for DemoEvents {}

        impl sails_rs::client::Identifiable for DemoEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <DemoImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for DemoImpl {
            type Event = DemoEvents;
        }
    }
}
