// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Usage: cd frontend && npx tsx ../scripts/scaffold-client.ts [idl-path]
// Default IDL path: src/assets/demo.idl

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  getPrimitiveLabel, getTypeLabel, primToTs, getTsType,
  methodIcon, isSmallNumeric, isBigNumeric, isHexType, defaultValueStr,
} from "./scaffold-types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND_DIR = resolve(__dirname, "..", "frontend");

// --- IDL Parsing (uses sails-js-parser) ---

async function parseIdl(idlText: string) {
  // Import from frontend/node_modules since that's where the dep lives
  const parserPath = resolve(FRONTEND_DIR, "node_modules/sails-js-parser/lib/index.js");
  const { SailsIdlParser } = await import(parserPath);
  const parser = await SailsIdlParser.new();
  return parser.parse(idlText);
}

// --- Naming conventions ---
// Queries: strip "Get" prefix, add "query" prefix. GetState -> queryState, GetCounter -> queryCounter
// Commands: add "tx" prefix. Increment -> txIncrement, SendMessage -> txSendMessage

function queryFnName(methodName: string): string {
  const stripped = methodName.startsWith("Get")
    ? methodName.slice(3)
    : methodName;
  return `query${stripped}`;
}

function txFnName(methodName: string): string {
  return `tx${methodName}`;
}

// --- Parameter type for codegen ---

interface ParamInfo {
  name: string;
  typeLabel: string;
  tsType: string;
  def: any;
}

function getParams(func: any): ParamInfo[] {
  return func.params.map((p: any) => ({
    name: p.name,
    typeLabel: getTypeLabel(p.def),
    tsType: getTsType(p.def),
    def: p.def,
  }));
}

// --- Type collection ---

function collectUserDefinedTypes(def: any, names: Set<string>): void {
  if (!def) return;
  if (def.isUserDefined) {
    names.add(def.asUserDefined.name);
  } else if (def.isVec) {
    collectUserDefinedTypes(def.asVec.def, names);
  } else if (def.isOptional) {
    collectUserDefinedTypes(def.asOptional.def, names);
  } else if (def.isStruct) {
    for (const f of def.asStruct.fields) {
      collectUserDefinedTypes(f.def, names);
    }
  } else if (def.isResult) {
    collectUserDefinedTypes(def.asResult.ok.def, names);
    collectUserDefinedTypes(def.asResult.err.def, names);
  } else if (def.isMap) {
    collectUserDefinedTypes(def.asMap.key.def, names);
    collectUserDefinedTypes(def.asMap.value.def, names);
  } else if (def.isFixedSizeArray) {
    collectUserDefinedTypes(def.asFixedSizeArray.def, names);
  }
}

// --- Code generation ---

function generateTypeInterfaces(program: any): string[] {
  const lines: string[] = [];
  const types = program.types ?? [];
  for (const type of types) {
    const def = type.def;
    if (def?.isStruct) {
      lines.push(`export interface ${type.name} {`);
      for (const field of def.asStruct.fields) {
        lines.push(`  ${field.name}: ${getTsType(field.def)};`);
      }
      lines.push(`}`);
      lines.push(``);
    }
  }
  return lines;
}

function generateSailsClient(
  serviceName: string,
  queries: any[],
  commands: any[],
  program: any,
  idlRelPath: string
): string {
  const lines: string[] = [];

  // Header
  lines.push(
    `// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts`,
    `// Regenerate: cd frontend && npx tsx ../scripts/scaffold-client.ts`,
    `// Source IDL: ${idlRelPath}`,
    `// Custom helpers should go in a separate file (e.g., sails-helpers.ts)`,
    ``,
    `import type { GearApi } from "@gear-js/api";`,
    `import type { Sails } from "sails-js";`,
    `import type { SignerOptions } from "@polkadot/api/types";`,
    `import idlRaw from "@/assets/demo.idl?raw";`,
    ``,
  );

  // Type interfaces from IDL
  const typeLines = generateTypeInterfaces(program);
  if (typeLines.length > 0) {
    lines.push(`// -- Types from IDL --`, ``);
    lines.push(...typeLines);
  }

  // initSails boilerplate — caches on API, sets programId before returning
  lines.push(
    `let cachedSails: Promise<Sails> | null = null;`,
    `let cachedApi: GearApi | null = null;`,
    ``,
    `export async function initSails(api: GearApi, programId?: string): Promise<Sails> {`,
    `  // Invalidate cache if api instance changed (fixes stale connection after reconnect)`,
    `  if (cachedSails && cachedApi !== api) {`,
    `    cachedSails = null;`,
    `  }`,
    `  if (!cachedSails) {`,
    `    cachedApi = api;`,
    `    cachedSails = (async () => {`,
    `      const [{ Sails }, { SailsIdlParser }] = await Promise.all([`,
    `        import("sails-js"),`,
    `        import("sails-js-parser"),`,
    `      ]);`,
    `      const parser = await SailsIdlParser.new();`,
    `      const sails = new Sails(parser);`,
    `      sails.setApi(api);`,
    `      sails.parseIdl(idlRaw);`,
    `      return sails;`,
    `    })().catch((err) => {`,
    `      cachedSails = null;`,
    `      cachedApi = null;`,
    `      throw err;`,
    `    });`,
    `  }`,
    `  const sails = await cachedSails;`,
    `  if (programId) {`,
    `    sails.setProgramId(programId as \`0x\${string}\`);`,
    `  }`,
    `  return sails;`,
    `}`,
    ``,
  );

  // getService helper with actual service name
  lines.push(
    `function getService(sails: Sails) {`,
    `  return sails.services.${serviceName} ?? sails.services.${serviceName.toLowerCase()};`,
    `}`,
    ``,
  );

  // Query wrappers
  lines.push(`// -- Queries --`, ``);
  for (const q of queries) {
    const fnName = queryFnName(q.name);
    const params = getParams(q);
    const paramArgs = params.map((p) => `${p.name}: ${p.tsType}`).join(", ");
    const paramCall = params.map((p) => p.name).join(", ");
    const hasParams = params.length > 0;
    const returnType = getTsType(q.def);

    lines.push(
      `export async function ${fnName}(api: GearApi${hasParams ? `, ${paramArgs}` : ""}, programId?: string): Promise<${returnType}> {`,
      `  const sails = await initSails(api, programId);`,
      `  const service = getService(sails);`,
      `  return service.queries.${q.name}(${paramCall}).call();`,
      `}`,
      ``,
    );
  }

  // Transaction wrappers
  lines.push(`// -- Transactions --`, ``);
  for (const cmd of commands) {
    const fnName = txFnName(cmd.name);
    const params = getParams(cmd);
    const extraArgs = params
      .map((p) => `  ${p.name}: ${p.tsType},`)
      .join("\n");
    const paramCall = params.map((p) => p.name).join(", ");
    const returnType = getTsType(cmd.def);

    lines.push(
      `export async function ${fnName}(`,
      `  api: GearApi,`,
      `  programId: string,`,
      `  account: string,`,
    );
    if (params.length > 0) {
      lines.push(extraArgs);
    }
    lines.push(
      `  signer?: unknown,`,
      `  options?: { onSubmitted?: () => void },`,
      `): Promise<${returnType}> {`,
      `  const sails = await initSails(api, programId);`,
      `  const service = getService(sails);`,
      `  const tx = service.functions.${cmd.name}(${paramCall});`,
      `  const result = await tx`,
      `    .withAccount(account, signer ? { signer } as Partial<SignerOptions> : undefined)`,
      `    .calculateGas()`,
      `    .then(() => tx.signAndSend());`,
      `  options?.onSubmitted?.();`,
      `  return result.response();`,
      `}`,
      ``,
    );
  }

  // getIdlText
  lines.push(
    `/** Get the raw IDL text for the debug panel. */`,
    `export function getIdlText(): string {`,
    `  return idlRaw;`,
    `}`,
    ``,
  );

  return lines.join("\n");
}

// --- UI helpers for codegen ---

const HEADER = [
  `// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts`,
  `// Regenerate: cd frontend && ./node_modules/.bin/tsx ../scripts/scaffold-client.ts`,
  `// Feel free to customize — re-running the script will overwrite this file.`,
  ``,
].join("\n");

const ACCENTS = [
  "border-emerald-500/40",
  "border-amber-500/40",
  "border-sky-500/40",
  "border-violet-500/40",
  "border-rose-500/40",
];

/** Derive a unique variable prefix from method name: SendMessage -> sendMsg, Increment -> inc */
function varPrefix(name: string, allNames: string[]): string {
  const lower = name.charAt(0).toLowerCase() + name.slice(1);
  // Try progressively longer prefixes until unique
  for (let len = 3; len <= lower.length; len++) {
    const prefix = lower.slice(0, len);
    const collisions = allNames.filter((n) => {
      const other = n.charAt(0).toLowerCase() + n.slice(1);
      return other.slice(0, len) === prefix && n !== name;
    });
    if (collisions.length === 0) return prefix;
  }
  return lower;
}

// --- Generate ActionsPanel.tsx ---

function generateActionsPanel(
  serviceName: string,
  commands: any[],
  idlRelPath: string,
): string {
  const L: string[] = [];

  // Collect unique icons used by no-param commands (only they render icons in buttons)
  const cmdIcons = new Set(
    commands.filter((c) => c.params.length === 0).map((c) => methodIcon(c.name))
  );
  // Always need these for TxStatus
  const allIcons = new Set(["CircleNotch", "CheckCircle", "XCircle", ...cmdIcons]);
  const iconList = [...allIcons].sort().join(", ");

  // Imports
  const txImports = commands.map((c) => txFnName(c.name));
  L.push(HEADER);
  L.push(`import { useState } from "react";`);
  L.push(`import { motion, AnimatePresence } from "framer-motion";`);
  L.push(`import {`);
  L.push(`  ${iconList},`);
  L.push(`} from "@phosphor-icons/react";`);
  L.push(`import { useChainApi, useWallet } from "@/providers/chain-provider";`);
  L.push(`import {`);
  for (const name of txImports) {
    L.push(`  ${name},`);
  }
  L.push(`} from "@/lib/sails-client";`);
  L.push(``);

  // TxPhase type + TxStatus component (self-contained)
  L.push(`type TxPhase = "idle" | "signing" | "submitted" | "confirmed" | "error";`);
  L.push(``);
  L.push(`function TxStatus({`);
  L.push(`  phase, error, onDismiss,`);
  L.push(`}: {`);
  L.push(`  phase: TxPhase; error: string | null; onDismiss?: () => void;`);
  L.push(`}) {`);
  L.push(`  return (`);
  L.push(`    <AnimatePresence mode="wait">`);
  L.push(`      {phase !== "idle" && (`);
  L.push(`        <motion.div key={phase} initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 4 }} transition={{ type: "spring" as const, stiffness: 200, damping: 25 }} className={\`mt-2.5 \${phase === "error" ? "bg-red-500/5 border border-red-500/10 rounded-xl p-3" : "flex items-center gap-1.5"}\`} role="status" aria-live="polite">`);
  L.push(`          {phase === "signing" && (<><CircleNotch size={14} className="animate-spin text-amber-400" aria-hidden="true" /><span className="text-sm text-amber-400">Waiting for signature</span></>)}`);
  L.push(`          {phase === "submitted" && (<><CircleNotch size={14} className="animate-spin text-emerald-400" aria-hidden="true" /><span className="text-sm text-emerald-400">Processing</span></>)}`);
  L.push(`          {phase === "confirmed" && (<><CheckCircle size={14} weight="fill" className="text-emerald-400" aria-hidden="true" /><span className="text-sm text-emerald-400">Confirmed</span></>)}`);
  L.push(`          {phase === "error" && (<div className="flex items-start gap-2"><XCircle size={16} weight="fill" className="text-red-400 mt-0.5 flex-shrink-0" aria-hidden="true" /><span className="text-sm text-red-400 flex-1">{error}</span>{onDismiss && (<button onClick={onDismiss} aria-label="Dismiss error" className="text-red-400/60 hover:text-red-300 transition-colors flex-shrink-0 focus-visible:ring-2 focus-visible:ring-red-400/50 rounded"><XCircle size={14} weight="bold" aria-hidden="true" /></button>)}</div>)}`);
  L.push(`        </motion.div>`);
  L.push(`      )}`);
  L.push(`    </AnimatePresence>`);
  L.push(`  );`);
  L.push(`}`);
  L.push(``);

  // Main component
  L.push(`export function ActionsPanel({ onTxSuccess }: { onTxSuccess: () => void }) {`);
  L.push(`  const { api, apiStatus, programId } = useChainApi();`);
  L.push(`  const { account, signer, walletStatus } = useWallet();`);
  L.push(`  const disabled = !api || apiStatus !== "ready" || walletStatus !== "connected" || !account;`);
  L.push(``);

  const allCmdNames = commands.map((c: any) => c.name);

  // Per-command state hooks
  for (const cmd of commands) {
    const prefix = varPrefix(cmd.name, allCmdNames);
    const params = getParams(cmd);
    L.push(`  // ${cmd.name}`);
    L.push(`  const [${prefix}Phase, set${cmd.name}Phase] = useState<TxPhase>("idle");`);
    L.push(`  const [${prefix}Error, set${cmd.name}Error] = useState<string | null>(null);`);
    for (const p of params) {
      const def = defaultValueStr(p.typeLabel);
      L.push(`  const [${prefix}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}, set${cmd.name}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}] = useState(${def});`);
    }
    L.push(``);
  }

  // Per-command handler functions
  for (const cmd of commands) {
    const prefix = varPrefix(cmd.name, allCmdNames);
    const params = getParams(cmd);
    const fnName = txFnName(cmd.name);
    const paramVars = params.map(
      (p) => `${prefix}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}`
    );
    const callArgs = ["api", "programId", "account.address", ...paramVars, "signer"].join(", ");

    L.push(`  async function handle${cmd.name}() {`);
    L.push(`    if (!api || !account) return;`);

    // Client-side validation for each param
    for (const p of params) {
      const stateVar = `${prefix}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}`;
      if (p.typeLabel === "str" || p.typeLabel === "char") {
        L.push(`    if (!${stateVar} || !${stateVar}.trim()) {`);
        L.push(`      set${cmd.name}Error("${p.name} cannot be empty");`);
        L.push(`      set${cmd.name}Phase("error");`);
        L.push(`      return;`);
        L.push(`    }`);
      } else if (isSmallNumeric(p.typeLabel)) {
        L.push(`    if (${stateVar} < 1) {`);
        L.push(`      set${cmd.name}Error("${p.name} must be at least 1");`);
        L.push(`      set${cmd.name}Phase("error");`);
        L.push(`      return;`);
        L.push(`    }`);
      }
    }

    L.push(`    set${cmd.name}Phase("signing");`);
    L.push(`    set${cmd.name}Error(null);`);
    L.push(`    try {`);
    L.push(`      await ${fnName}(${callArgs}, {`);
    L.push(`        onSubmitted: () => set${cmd.name}Phase("submitted"),`);
    L.push(`      });`);
    L.push(`      set${cmd.name}Phase("confirmed");`);
    L.push(`      onTxSuccess();`);
    L.push(`      setTimeout(() => set${cmd.name}Phase("idle"), 3000);`);
    L.push(`    } catch (err) {`);
    L.push(`      set${cmd.name}Phase("error");`);
    L.push(`      set${cmd.name}Error(err instanceof Error ? err.message : "Transaction failed");`);
    L.push(`    }`);
    L.push(`  }`);
    L.push(``);
  }

  // Busy check
  const busyChecks = commands.map((cmd) => {
    const prefix = varPrefix(cmd.name, allCmdNames);
    return `${prefix}Phase === "signing" || ${prefix}Phase === "submitted"`;
  });
  L.push(`  const busy = ${busyChecks.join(" || ")};`);
  L.push(``);

  // Render
  L.push(`  return (`);
  L.push(`    <div className="rounded-2xl border border-zinc-800/50 bg-zinc-900/30 p-6 shadow-[0_8px_30px_-12px_rgba(0,0,0,0.4)]">`);
  L.push(`      <h2 className="text-sm font-medium text-zinc-400 mb-5">Actions</h2>`);
  L.push(``);
  L.push(`      {!account && (`);
  L.push(`        <div className="py-6 text-center">`);
  L.push(`          <p className="text-sm text-zinc-400">Connect your wallet to send transactions.</p>`);
  L.push(`        </div>`);
  L.push(`      )}`);
  L.push(``);
  L.push(`      <div className="space-y-0 divide-y divide-zinc-800/50">`);

  for (let i = 0; i < commands.length; i++) {
    const cmd = commands[i];
    const prefix = varPrefix(cmd.name, allCmdNames);
    const params = getParams(cmd);
    const isFirst = i === 0;
    const isLast = i === commands.length - 1;
    const divClass = isFirst ? "pb-5" : isLast ? "pt-5" : "py-5";

    L.push(`        {/* ${cmd.name} */}`);
    L.push(`        <div className="${divClass}">`);

    if (params.length === 0) {
      // No-param command: just a button
      L.push(`          <button`);
      L.push(`            onClick={handle${cmd.name}}`);
      L.push(`            disabled={disabled || busy}`);
      L.push(`            className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-emerald-600/80 text-emerald-50 text-base font-medium hover:bg-emerald-600 transition-colors disabled:opacity-30 disabled:cursor-not-allowed active:scale-[0.97] focus-visible:ring-2 focus-visible:ring-emerald-400/50 focus-visible:outline-none"`);
      L.push(`          >`);
      L.push(`            <${methodIcon(cmd.name)} size={16} weight="bold" aria-hidden="true" />`);
      L.push(`            ${cmd.name}`);
      L.push(`          </button>`);
    } else {
      // Command with params
      const cmdId = cmd.name.toLowerCase();
      L.push(`          <div className="flex gap-2 items-center">`);

      for (const p of params) {
        const stateVar = `${prefix}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}`;
        const setterVar = `set${cmd.name}${p.name.charAt(0).toUpperCase() + p.name.slice(1)}`;
        const inputId = `${cmdId}-${p.name}`;

        if (p.typeLabel === "str" || p.typeLabel === "char") {
          L.push(`            <div className="flex-1 relative">`);
          L.push(`              <label htmlFor="${inputId}" className="sr-only">${p.name}</label>`);
          L.push(`              <input id="${inputId}" type="text" autoComplete="off" value={${stateVar}} onChange={(e) => ${setterVar}(e.target.value)} placeholder="${p.name}\u2026" className="w-full px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-colors placeholder:text-zinc-500" />`);
          L.push(`              {${stateVar}.length > 0 && <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-zinc-600">{${stateVar}.length}</span>}`);
          L.push(`            </div>`);
        } else if (isSmallNumeric(p.typeLabel)) {
          L.push(`            <label htmlFor="${inputId}" className="text-sm text-zinc-400">${p.name}</label>`);
          L.push(`            <input id="${inputId}" type="number" autoComplete="off" value={${stateVar}} onChange={(e) => ${setterVar}(Number(e.target.value))} className="w-24 px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm font-mono border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-colors" />`);
        } else if (isBigNumeric(p.typeLabel)) {
          L.push(`            <label htmlFor="${inputId}" className="sr-only">${p.name}</label>`);
          L.push(`            <input id="${inputId}" type="text" autoComplete="off" value={${stateVar}} onChange={(e) => ${setterVar}(e.target.value)} placeholder="0" className="w-32 px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm font-mono border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-colors" />`);
          L.push(`            <span className="text-sm text-zinc-400">${p.name} (${p.typeLabel})</span>`);
        } else if (isHexType(p.typeLabel)) {
          L.push(`            <label htmlFor="${inputId}" className="sr-only">${p.name}</label>`);
          L.push(`            <input id="${inputId}" type="text" autoComplete="off" value={${stateVar}} onChange={(e) => ${setterVar}(e.target.value)} placeholder="0x\u2026" className="flex-1 px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm font-mono border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-colors placeholder:text-zinc-500" />`);
        } else if (p.typeLabel === "bool") {
          L.push(`            <label className="flex items-center gap-2 text-sm text-zinc-300"><input id="${inputId}" type="checkbox" checked={${stateVar}} onChange={(e) => ${setterVar}(e.target.checked)} className="rounded" />${p.name}</label>`);
        } else {
          // Fallback: text input for complex types
          L.push(`            <label htmlFor="${inputId}" className="sr-only">${p.name}</label>`);
          L.push(`            <input id="${inputId}" type="text" autoComplete="off" value={${stateVar}} onChange={(e) => ${setterVar}(e.target.value)} placeholder="${p.name} (${p.typeLabel})" className="flex-1 px-4 py-2.5 rounded-xl bg-zinc-950 text-zinc-200 text-sm border border-zinc-800 focus:border-emerald-500/50 focus:outline-none focus:ring-1 focus:ring-emerald-500/20 transition-colors placeholder:text-zinc-500" />`);
        }
      }

      L.push(`            <button onClick={handle${cmd.name}} disabled={disabled || busy} className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-zinc-800 text-zinc-300 text-sm hover:bg-zinc-700 transition-colors disabled:opacity-30 active:scale-[0.97] ml-auto focus-visible:ring-2 focus-visible:ring-emerald-400/50 focus-visible:outline-none">${cmd.name}</button>`);
      L.push(`          </div>`);
    }

    L.push(`          <TxStatus phase={${prefix}Phase} error={${prefix}Error} onDismiss={() => { set${cmd.name}Phase("idle"); set${cmd.name}Error(null); }} />`);
    L.push(`        </div>`);
  }

  L.push(`      </div>`);
  L.push(`    </div>`);
  L.push(`  );`);
  L.push(`}`);
  L.push(``);

  return L.join("\n");
}

// --- Generate StatePanel.tsx ---

function resolveStructFields(program: any, typeDef: any): any[] | null {
  if (!typeDef) return null;
  if (typeDef.isStruct) return typeDef.asStruct.fields;
  if (typeDef.isUserDefined) {
    try {
      const type = program.getTypeByName(typeDef.asUserDefined.name);
      if (type && type.def && type.def.isStruct) return type.def.asStruct.fields;
    } catch { /* type not found */ }
  }
  return null;
}

function generateStatePanel(
  queries: any[],
  program: any,
  idlRelPath: string,
): string {
  const L: string[] = [];

  // Deduplicate: if a struct query (e.g. GetState) has fields that overlap with
  // scalar queries (e.g. GetCounter returns counter, GetState.counter exists),
  // skip the scalar queries to avoid showing the same data twice.
  const structQueryFields = new Set<string>();
  for (const q of queries) {
    const fields = resolveStructFields(program, q.def);
    if (fields) {
      for (const f of fields) {
        structQueryFields.add(f.name.toLowerCase());
      }
    }
  }

  const dedupedQueries = queries.filter((q: any) => {
    // Keep struct/vec queries
    const fields = resolveStructFields(program, q.def);
    if (fields) return true;
    if (q.def?.isVec) return true;
    // For scalar queries, skip if a struct query already covers this field
    const displayName = (q.name.startsWith("Get") ? q.name.slice(3) : q.name).toLowerCase();
    if (structQueryFields.has(displayName)) return false;
    return true;
  });

  // Figure out which queries return structs vs scalars vs vecs
  const queryInfos = dedupedQueries.map((q) => {
    const fields = resolveStructFields(program, q.def);
    const isVec = q.def?.isVec;
    const vecFields = isVec ? resolveStructFields(program, q.def.asVec?.def) : null;
    return {
      func: q,
      fnName: queryFnName(q.name),
      displayName: q.name.startsWith("Get") ? q.name.slice(3) : q.name,
      structFields: fields,
      isVec,
      vecFields,
      typeLabel: getTypeLabel(q.def),
    };
  });

  // Build query imports and collect type names used in return types
  const queryImports = queryInfos.map((qi) => qi.fnName);
  const usedTypeNames = new Set<string>();
  for (const qi of queryInfos) {
    collectUserDefinedTypes(qi.func.def, usedTypeNames);
  }

  L.push(HEADER);
  L.push(`import { useState, useEffect, useCallback } from "react";`);
  L.push(`import { motion } from "framer-motion";`);
  L.push(`import { ArrowsClockwise, Pulse } from "@phosphor-icons/react";`);
  L.push(`import { CopyAddress } from "@/components/CopyAddress";`);
  L.push(`import { useChainApi, useWallet } from "@/providers/chain-provider";`);
  L.push(`import {`);
  for (const name of queryImports) {
    L.push(`  ${name},`);
  }
  for (const typeName of usedTypeNames) {
    L.push(`  type ${typeName},`);
  }
  L.push(`} from "@/lib/sails-client";`);
  L.push(``);

  // MetricRow + Skeleton components
  L.push(`function MetricRow({ value, label, accentColor = "border-emerald-500/40" }: { value: string | number; label: string; accentColor?: string }) {`);
  L.push(`  return (`);
  L.push(`    <div className={\`border-l-2 \${accentColor} pl-4 py-2\`}>`);
  L.push(`      <div className="font-mono text-3xl tracking-tighter text-zinc-300 leading-none">{String(value)}</div>`);
  L.push(`      <div className="text-sm text-zinc-400 mt-1.5">{label}</div>`);
  L.push(`    </div>`);
  L.push(`  );`);
  L.push(`}`);
  L.push(``);
  L.push(`function SkeletonMetric() {`);
  L.push(`  return (`);
  L.push(`    <div className="border-l-2 border-zinc-800 pl-4 py-2">`);
  L.push(`      <div className="h-9 w-16 rounded-lg bg-zinc-800/60 shimmer" />`);
  L.push(`      <div className="h-3 w-20 rounded bg-zinc-800/60 shimmer mt-2" />`);
  L.push(`    </div>`);
  L.push(`  );`);
  L.push(`}`);
  L.push(``);

  // Main component
  L.push(`export function StatePanel({ refreshTrigger }: { refreshTrigger: number }) {`);
  L.push(`  const { api, apiStatus, programId } = useChainApi();`);
  L.push(`  const { account } = useWallet();`);

  // State for each query result — typed from IDL
  for (const qi of queryInfos) {
    const returnType = getTsType(qi.func.def);
    const stateVar = qi.displayName.charAt(0).toLowerCase() + qi.displayName.slice(1);
    L.push(`  const [${stateVar}Data, set${qi.displayName}Data] = useState<${returnType} | null>(null);`);
  }

  L.push(`  const [loading, setLoading] = useState(true);`);
  L.push(`  const [error, setError] = useState<string | null>(null);`);
  L.push(`  const [pollInterval, setPollInterval] = useState(5000);`);
  L.push(``);

  // Fetch function
  L.push(`  const fetchState = useCallback(async () => {`);
  L.push(`    if (!api || apiStatus !== "ready") return;`);
  L.push(`    try {`);
  L.push(`      const [${queryInfos.map((qi) => `r_${qi.displayName.toLowerCase()}`).join(", ")}] = await Promise.all([`);
  for (const qi of queryInfos) {
    L.push(`        ${qi.fnName}(api, programId),`);
  }
  L.push(`      ]);`);
  for (const qi of queryInfos) {
    const stateVar = qi.displayName.charAt(0).toLowerCase() + qi.displayName.slice(1);
    L.push(`      set${qi.displayName}Data(r_${qi.displayName.toLowerCase()});`);
  }
  L.push(`      setError(null);`);
  L.push(`      setLoading(false);`);
  L.push(`      setPollInterval(5000);`);
  L.push(`    } catch (err) {`);
  L.push(`      setError(err instanceof Error ? err.message : "Failed to read state");`);
  L.push(`      setLoading(false);`);
  L.push(`      setPollInterval((prev) => Math.min(prev * 2, 60000));`);
  L.push(`    }`);
  L.push(`  }, [api, apiStatus, programId]);`);
  L.push(``);

  // Effects
  L.push(`  useEffect(() => { fetchState(); }, [fetchState, refreshTrigger]);`);
  L.push(``);
  L.push(`  useEffect(() => {`);
  L.push(`    if (!api || apiStatus !== "ready") return;`);
  L.push(`    const id = setInterval(fetchState, pollInterval);`);
  L.push(`    return () => clearInterval(id);`);
  L.push(`  }, [api, apiStatus, fetchState, pollInterval]);`);
  L.push(``);

  // Check if we have any data
  const firstDataVar = queryInfos.length > 0
    ? `${queryInfos[0].displayName.charAt(0).toLowerCase() + queryInfos[0].displayName.slice(1)}Data`
    : "null";

  // Render
  L.push(`  return (`);
  L.push(`    <div className="rounded-2xl border border-zinc-800/50 bg-zinc-900/30 p-6 shadow-[0_8px_30px_-12px_rgba(0,0,0,0.4)]">`);
  L.push(`      <div className="flex items-center justify-between mb-6">`);
  L.push(`        <h2 className="text-sm font-medium text-zinc-400">Program State</h2>`);
  L.push(`        <button onClick={fetchState} aria-label="Refresh state" className="p-2 rounded-lg text-zinc-400 hover:text-zinc-300 hover:bg-zinc-800/50 transition-colors active:scale-[0.93] focus-visible:ring-2 focus-visible:ring-emerald-400/50 focus-visible:outline-none">`);
  L.push(`          <ArrowsClockwise size={16} weight="bold" aria-hidden="true" />`);
  L.push(`        </button>`);
  L.push(`      </div>`);
  L.push(``);

  // Loading state
  L.push(`      {loading && !${firstDataVar} ? (`);
  L.push(`        <div className="space-y-6">`);
  L.push(`          <SkeletonMetric /><SkeletonMetric /><SkeletonMetric />`);
  L.push(`        </div>`);

  // Error state
  L.push(`      ) : error && !${firstDataVar} ? (`);
  L.push(`        <div className="rounded-xl bg-red-500/5 border border-red-500/10 p-4">`);
  L.push(`          <p className="text-sm text-red-400">{error}</p>`);
  L.push(`          <button onClick={fetchState} className="mt-2 text-sm text-red-400/80 underline underline-offset-2 hover:text-red-300 focus-visible:ring-2 focus-visible:ring-red-400/50 rounded focus-visible:outline-none">Try again</button>`);
  L.push(`        </div>`);

  // Empty state
  L.push(`      ) : !${firstDataVar} ? (`);
  L.push(`        <div className="py-8 text-center">`);
  L.push(`          <Pulse size={32} weight="duotone" className="mx-auto text-zinc-500 mb-3" />`);
  L.push(`          <p className="text-sm text-zinc-400">{account ? "Waiting for data. Send a transaction to get started." : "Connect your wallet to read program state."}</p>`);
  L.push(`        </div>`);

  // Data display
  L.push(`      ) : (`);
  L.push(`        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}>`);
  L.push(`          <div className="space-y-5">`);

  let accentIdx = 0;
  for (const qi of queryInfos) {
    const dataVar = `${qi.displayName.charAt(0).toLowerCase() + qi.displayName.slice(1)}Data`;

    if (qi.structFields) {
      // Struct: render each field as a MetricRow
      for (const field of qi.structFields) {
        const fieldLabel = field.name;
        const accent = ACCENTS[accentIdx % ACCENTS.length];
        const fieldTypeLabel = getTypeLabel(field.def);

        if (fieldTypeLabel === "opt actor_id" || fieldTypeLabel === "actor_id") {
          // Address field: use CopyAddress component
          L.push(`            {${dataVar}?.${fieldLabel} && (`);
          L.push(`              <div className="flex items-center gap-2 text-sm text-zinc-400 py-2">`);
          L.push(`                <span>${fieldLabel}:</span>`);
          L.push(`                <CopyAddress address={String(${dataVar}.${fieldLabel})} />`);
          L.push(`              </div>`);
          L.push(`            )}`);
        } else {
          // Use type-aware fallback: "" for string types, 0 for numeric
          const isStringField = fieldTypeLabel === "str" || fieldTypeLabel === "char";
          const fallback = isStringField ? '""' : "0";
          L.push(`            <MetricRow value={${dataVar}?.${fieldLabel} ?? ${fallback}} label="${fieldLabel}" accentColor="${accent}" />`);
          accentIdx++;
        }
      }
    } else if (qi.isVec && qi.vecFields) {
      // Vec of structs: render each item using field metadata
      const vecTypeName = qi.func.def?.asVec?.def?.isUserDefined
        ? qi.func.def.asVec.def.asUserDefined.name
        : "any";
      L.push(`            {${dataVar} && ${dataVar}.length > 0 && (`);
      L.push(`              <div className="border-t border-zinc-800/50 pt-4 mt-4">`);
      L.push(`                <h3 className="text-sm text-zinc-400 mb-3">${qi.displayName} ({${dataVar}.length})</h3>`);
      L.push(`                <div className="max-h-48 overflow-y-auto overflow-x-hidden divide-y divide-zinc-800/30">`);
      // Use first text field + index as composite key for stable identity
      const keyField = qi.vecFields.find((f: any) => {
        const tl = getTypeLabel(f.def);
        return tl !== "actor_id" && tl !== "opt actor_id";
      });
      const keyExpr = keyField ? `\`\${item.${keyField.name}}-\${i}\`` : "i";
      L.push(`                  {${dataVar}.map((item: ${vecTypeName}, i: number) => (`);
      L.push(`                    <div key={${keyExpr}} className="py-2 text-sm text-zinc-400 min-w-0">`);

      // Render each field based on type
      const addressFields: string[] = [];
      const textFields: string[] = [];
      for (const field of qi.vecFields) {
        const ftl = getTypeLabel(field.def);
        if (ftl === "actor_id" || ftl === "opt actor_id") {
          addressFields.push(field.name);
        } else {
          textFields.push(field.name);
        }
      }
      if (addressFields.length > 0 || textFields.length > 0) {
        L.push(`                      <div className="flex items-start gap-2 min-w-0">`);
        for (const af of addressFields) {
          L.push(`                        {item.${af} && <CopyAddress address={String(item.${af})} />}`);
        }
        for (const tf of textFields) {
          L.push(`                        <span className="break-all">{String(item.${tf} ?? "")}</span>`);
        }
        L.push(`                      </div>`);
      } else {
        L.push(`                      <span className="break-all">{JSON.stringify(item)}</span>`);
      }

      L.push(`                    </div>`);
      L.push(`                  ))}`);
      L.push(`                </div>`);
      L.push(`              </div>`);
      L.push(`            )}`);
    } else {
      // Simple scalar or unknown: single MetricRow
      const accent = ACCENTS[accentIdx % ACCENTS.length];
      L.push(`            <MetricRow value={${dataVar} ?? "—"} label="${qi.displayName}" accentColor="${accent}" />`);
      accentIdx++;
    }
  }

  L.push(`          </div>`);
  L.push(`        </motion.div>`);
  L.push(`      )}`);
  L.push(`    </div>`);
  L.push(`  );`);
  L.push(`}`);
  L.push(``);

  return L.join("\n");
}

// --- Main ---

async function main() {
  const idlPath = process.argv[2] || resolve(FRONTEND_DIR, "src/assets/demo.idl");
  const absIdlPath = resolve(idlPath);

  let idlText: string;
  try {
    idlText = readFileSync(absIdlPath, "utf-8");
  } catch {
    console.error(`ERROR: IDL file not found at ${absIdlPath}`);
    console.error(`Expected path: frontend/src/assets/demo.idl`);
    process.exit(1);
  }

  console.log(`Parsing IDL: ${absIdlPath}`);
  let program: any;
  try {
    program = await parseIdl(idlText);
  } catch (err) {
    console.error(`ERROR: Failed to parse IDL`);
    console.error(err);
    process.exit(1);
  }

  const services = program.services;
  if (services.length === 0) {
    console.error("ERROR: No services found in IDL");
    process.exit(1);
  }

  const service = services[0];
  const serviceName = service.name;
  console.log(`Service: ${serviceName} (${service.funcs.length} methods)`);

  const queries = service.funcs.filter((f: any) => f.isQuery);
  const commands = service.funcs.filter((f: any) => !f.isQuery);

  console.log(`  Queries: ${queries.map((q: any) => q.name).join(", ")}`);
  console.log(`  Commands: ${commands.map((c: any) => c.name).join(", ")}`);

  const idlRelPath = "src/assets/demo.idl";

  // 1. Generate sails-client.ts
  const clientOutput = generateSailsClient(serviceName, queries, commands, program, idlRelPath);
  const clientPath = resolve(FRONTEND_DIR, "src/lib/sails-client.ts");
  writeFileSync(clientPath, clientOutput);
  console.log(`Generated: ${clientPath}`);

  // 2. Generate ActionsPanel.tsx
  const actionsOutput = generateActionsPanel(serviceName, commands, idlRelPath);
  const actionsPath = resolve(FRONTEND_DIR, "src/components/ActionsPanel.tsx");
  writeFileSync(actionsPath, actionsOutput);
  console.log(`Generated: ${actionsPath}`);

  // 3. Generate StatePanel.tsx
  const stateOutput = generateStatePanel(queries, program, idlRelPath);
  const statePath = resolve(FRONTEND_DIR, "src/components/StatePanel.tsx");
  writeFileSync(statePath, stateOutput);
  console.log(`Generated: ${statePath}`);
}

// Run when executed directly (not when imported for testing)
const isDirectRun = process.argv[1]?.endsWith("scaffold-client.ts");
if (isDirectRun) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

