// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Regenerate: cd frontend && npx tsx ../scripts/scaffold-client.ts
// Source IDL: src/assets/demo.idl
// Custom helpers should go in a separate file (e.g., sails-helpers.ts)

import type { GearApi } from "@gear-js/api";
import idlRaw from "@/assets/demo.idl?raw";

let cachedSails: Promise<unknown> | null = null;
let cachedApi: GearApi | null = null;

export async function initSails(api: GearApi) {
  // Invalidate cache if api instance changed (fixes stale connection after reconnect)
  if (cachedSails && cachedApi !== api) {
    cachedSails = null;
  }
  if (!cachedSails) {
    cachedApi = api;
    cachedSails = (async () => {
      const [{ Sails }, { SailsIdlParser }] = await Promise.all([
        import("sails-js"),
        import("sails-js-parser"),
      ]);
      const parser = await SailsIdlParser.new();
      const sails = new Sails(parser);
      sails.setApi(api);
      sails.parseIdl(idlRaw);

      const programId = import.meta.env.VITE_PROGRAM_ID;
      if (programId) {
        sails.setProgramId(programId as `0x${string}`);
      }

      return sails;
    })().catch((err) => {
      cachedSails = null;
      cachedApi = null;
      throw err;
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return cachedSails as Promise<any>;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getService(sails: any): any {
  return sails?.services?.Demo ?? sails?.services?.demo;
}

// -- Queries --

export async function queryCounter(api: GearApi): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetCounter().call();
}

export async function queryGreeting(api: GearApi): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetGreeting().call();
}

export async function queryMessages(api: GearApi): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetMessages().call();
}

export async function queryState(api: GearApi): Promise<unknown> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetState().call();
}

// -- Transactions --

export async function txHandlePing(
  api: GearApi,
  account: string,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.HandlePing();
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txIncrement(
  api: GearApi,
  account: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.Increment();
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSchedulePing(
  api: GearApi,
  account: string,
  delay: number,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SchedulePing(delay);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSendMessage(
  api: GearApi,
  account: string,
  text: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SendMessage(text);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSetGreeting(
  api: GearApi,
  account: string,
  greeting: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SetGreeting(greeting);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

/** Get the raw IDL text for the debug panel. */
export function getIdlText(): string {
  return idlRaw;
}
